### ISSUE TITLE
Unable to download from the marketplace

### ISSUE THREAD

**Issue by Probably-Mike** [microsoft/vs-intellicode#17]
Using Visual Studio 2017 professional as that is the newest licence we have, and have been issued with a new laptop and would like install IntelliCode again, but cannot find it anywhere to download or install.

Searching within Visual Studio does not find it, also searching the marketplace does not find it.

The link in the README.md here, and from various Google searched this page, but the extension is not there.
https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.VSIntelliCode

How can I get this to install again?
Many thanks,
Mike

**Comment by HashGrammer** [comment]
I am having the same issue, after much frustration trying to google, or find an alternative source for the VSXI to install this for 2017 Enterprise, I too would like some closure here. Has this been shadow removed as compatible with 2017 or is it just a problem with microsoft servers like when ML.NET meta resources went down last week?

Not being able to use intellicode is costing me a ridiculous amount of extra keystrokes. At the very least would should be provided with a link to the last working version with 2017 on an "as-is" basis.

**Comment by markw-t** [comment]
Hi folks. 

I am afraid we are no longer supporting or maintaining IntelliCode for Visual Studio 2017. The extension has now been removed from the marketplace.

You can acquire IntelliCode as part of the in-box installation for Visual Studio 2019 in releases from 16.3 onwards.

My apologies for the redundant link in the Visual Studio Code readme; we will be removing that in an upcoming update to that extension.

Regards
Mark

**Comment by Mike-NotFound** [comment]
I understand the it is no longer supported for Visual Studio 2017, but like @HashGrammer am finding not having it is slowing down productivity after having used it on my previous laptop, which it still works on!

I also put the question up at https://developercommunity.visualstudio.com/t/Unable-to-install-IntelliCode/1391423 and had the same response, no longer supported, issue closed.

No everyone can afford to upgrade every new version, the chances of getting an upgrade to VS 2019 is relatively slim for me.

Is there anyway to supply the last version of the vsix file to download for VS 2017.  Not expecting any support with this, it is such a useful tool to have.

**Comment by HashGrammer** [comment]
@markw-t 

As Mike-NotFound stated, you guys should *at least* supply the very last VSIX that supported VS 2017 with an AS-IS, No-Support disclaimer. It may not have been fully developed, and may not be perfect, but it will still save us thousands of keystrokes until our companies can afford to upgrade us to a 2019 license. Please don't let the developers suffer at the hands of corporate budgets during a pandemic...

> No everyone can afford to upgrade every new version, the chances of getting an upgrade to VS 2019 is relatively slim for me.
> 
> Is there anyway to supply the last version of the vsix file to download for VS 2017. Not expecting any support with this, it is such a useful tool to have.

**Comment by DeeJayhX** [comment]
Of course. I reformat and now I'm just permanently without intellicode? @markw-t please tell me what the other guys mentioned is possible. There are plenty of us stuck on 2017 still and, while I don't expect any support, I would at least like the functionality it was providing a mere 24 hours ago...

**Comment by Mike-NotFound** [comment]
@markw-t At the moment there is zero chance of me getting an upgrade to VS 2019, and for whatever reason Microsoft decide to pull this very useful extension from VS 2017.
The really silly thing in all of this is that VS 2017 itself is supported till 2027 https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-servicingarchive-vs

There must be a way to provide the download for the last version of Intellicode for VS 2017?
